service: aws-serverless-nodejs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  generate-hello:
    handler: src/functions/generate-hello/index.handler
    package:
      individually: true
      patterns:
        - "!**"
        - "src/shared/**"
        - "src/functions/generate-hello/**"
    events:
      - httpApi:
          path: /generate-hello
          method: get
  
  generate-world:
    handler: src/functions/generate-world/handler.run
    package:
      individually: true
      patterns:
        - "!**"
        - "src/shared/**"
        - "src/functions/generate-world/**"
    events:
      - httpApi:
          path: /generate-world
          method: get

plugins:
  - serverless-offline
